.Dd July 9, 2023
.Os
.Dt LC 1
.Sh NAME
.Nm lc
.Nd list directory contents custom-classified-colorfully
.Sh SYNOPSIS
.Nm
.Bk -words
.Op Fl OPTIONS..
.Op Fl -
.Op Cm PATHS..
.Ek
.Sh DESCRIPTION
.Nm
lists directory contents like
.Xr ls 1
in a filtered, sorted, tabular way, but with idea factoring tuned towards
more customizability.
.Nm
does not come with any built-in configuration, but the distribution does ship
with one which may serve as a starting point.
.Pp
There are quite a few specification nano-languages with many sometimes terse
codes { after the style of
.Xr find 1
&
.Xr strftime 3
} that drive all of this.  Though the source code will always be the best
reference, not everyone has the energy to learn Nim as well as all these bespoke
nano-langs.  While \fBlc --help\fP gives a quick reference, this present
document goes into more detail.  Even more details, rationale, and even screen
shots are available at github.com/c-blake/lc .
.Sh "OPTIONS (AKA FLAGS)"
Defaults are in () except for boolean flags which all default to false.
It is not expected that you will often/ever issue more involved options like
\fB--kind\fP, \fB--color\fP & \fB--ageFmt\fP interactively.  Rather they will
be in a config file, but options syntax is unified with that.  It may be easier
to learn how to drive
.Nm
from its example configuration files.
.Ss "File typology / taxonomy"
.Bl -hang -width MM
.It Sy "-k=, --kind=" ( Em "{}" ) Em "[TYPE-NAME-BINDINGS/DEFINITION STRINGS]"
where each string is: \fBNAME RELATION PARAMS\fP with 3 or more fields are
whitespace-separated and:
.Bl -tag -width "asciiChars | cset" -compact -offset indent
.It Em RELATION
PARAMS
.It Em asciiChars | cset
param=str of chars base name can have
.It Em Suffix | SFX
case-sensitive base name suffixes
.It Em suffix | sfx
case-insensitive base name suffixes
.It Em Prefix | PFX
case-sensitive base name prefixes
.It Em prefix | pfx
case-insensitive base name prefixes
.It Em perlRx | pcr
Perl-Compatible Regexes match base name
.It Em uid
numeric uids of file owners
.It Em gid
numeric gids of file file owners
.It Em user
exact string user names for file owners
.It Em group
exact string group names for file owners
.It Em magic | mag
pcRes matching a
.Xr libmagic 3
description 
.It Em extension | ext
parameter \fBX.so:FUNC\fP applied to paths != 0
.It Em any
matches any one of listed kind names
.It Em all
matches all one of listed kind names
.It Em none
matches no listed kind names
.El
BUILTIN TYPE \fBNAME\fRs:
.Bl -tag -width worldWritable -compact
.It Em regular
Is a regular file
.It Em directory
Is a directory
.It Em blockDevice
Is a block device special file
.It Em charDevice
Is a character device special file
.It Em fifo
Is a FIFO / named pipe special file
.It Em socket
Is a Unix domain socket special file
.It Em symLink
Is any symbolic link special file
.It Em -symLink
Is a symLink pointing to a missing file
.It Em +symLink
Is a symLink pointing to a present file
.It Em hardLinks
Non-(dir|symLink) file with hard link count > 1
.It Em executable
File is executable non-(dir|symLink)
.It Em suid
Is setuid & executable
.It Em sgid
Is setgid & executable
.It Em tmpDir
Is a directory with sticky bit set (like /tmp)
.It Em worldWritable
world writable by user (but not sticky)
.It Em unReadable
unreadable (by user) file/untraversable dir
.It Em oddPerm
Has odd permissions: u+s & (!x | !reg), g+s & g-x, dir+t & !o+w, !(u >= g >= o), +w & -r
.It Em IMMUTABLE
statx - has immutable attribute
.It Em APPENDONLY
statx - has append-only attribute
.It Em COMPRESSED
statx - has compressed attribute
.It Em ENCRYPTED
statx - has encrypted attribute
.It Em NODUMP
statx - has NoDump attribute
.It Em AUTOMOUNT
statx - has AutoMount attribute
.It Em CAPABILITY
Linux - has some Linux FS Capability
.It Em ACL
has some ACL
.El
\fBNOTE\fP: in config files / on the command-line, you may usually use \fIany
unique prefix\fP to refer to file kind names.
.El
.Ss "Formatting & Sorting"
.Bl -hang -width MM
.It \fB-c=, --color=\fP ( \fI{}\fP ) Em RenderSpecificationStrings
each with syntax \fBNAME[:KEY[:SLOT[:ICON]]] ATTR ATTR..\fP where whitespace
amounts do not matter and:
.Bl -tag -width "NAME -" -compact -offset indent
.It Em NAME -
(as in --kind) | \fIsize{BKMGT}\fP | \fIperm{0-7}\fP
.It Em KEY -
optional 0..255 \fISORT/ORDER\fP key
.It Em SLOT -
optional format slot/dimension (for layers)
.It Em ICON -
optional UTF-8 icon string
.It Em ATTR -
color/text attr specs as in TEXT ATTRIBUTE section
.El
\fB--color\fP is really about more than colors.  It a meta-type specification
directive.  The \fIKEY\fP lets you decide where in \fB--order\fP a given kind
will fit as well as which slot is used for this kind \fINAME\fP.  E.g., you may
want to give "interface files" a lower integer \fIKEY\fP than "implementations",
if the alphabet swaps that (e.g. \fB.h\fP, \fB.c\fP).
.Pp
When might you want a different slot?  When some quality is "importantly"
independent of other qualities.  While typology is largely user-defined, a
simple example would be a primary dimension based on filename extensions or
based on i-node metadata.  Going further with this example, one slot is about
\fIhow you might\fP operate on a file and could be bound to many foreground
colors like media files one color, source code another, etc.  A second dimension
might then be permissions such as \fIwhether you are allowed\fP to operate.  You
can denote disallowed operation by \fBstruck\fP based on a file type test in an
independent slot.  In this way the independence of the input matches independent
layering of the output.  How much you can layer is very limited.
.Pp
\fIICON\fP should be self-explanatory and \fIATTR\fP is covered in the below
\fBTEXT ATTRIBUTE / COLOR SPECIFICATION\fP section.
.Pp
Besides text colors/attributes for file types, \fB--color\fR also lets you set
how certain value-dependent columns are rendered like file size & permissions
via \fIpseudo-type-names\fP like \fBsizeM\fP for size in megabytes or \fBperm5\fP
for the octal code indicating "r-x" permissions.
.It Sy "-a=, --ageFmt=" ( Em "{}" )   Em FileAgeFormatStrings
each with syntax: \fI<FileAge>@[-+]<STRFTIME_FMT>\fP where:
.Bl -tag -width STRFTIME -compact -offset indent
.It Em FileAge
is {seconds | 'FUTURE' | 'ANYTIME'}
.It Em \&'+'
means the alternate format
.It Em '-'
means plain mode format
.It Em strftime
%CODEs are any strftime & %DIGIT
.It Order can matter here; Arrange oldest to youngest.
.El
For example, \fB-a86400@%{purple}y%{blue}m%{cyan}d
-a0@%{green}H%{yellow}M%{red}S\fP will render file times older than 86400
seconds (1 day) in a "cooler" hue (blue side) by date (%y%m%d) but younger files
in a "warmer" hue by time of day (%H%M%S).
.It \fB-o=, --order=\fP ( \fI''\fP ) [-]X[-]Y[-]Z... keys to multi-level sort files by.
See FORMAT & ORDER CODES section of this page for X,Y,Z,...
.It \fB-f=, --format=\fP ( \fI%f\fP ) "%X %{bold}Y %-Z .." dirent format; %-Z left-aligns.
See FORMAT & ORDER CODES section of this page for X,Y,Z,...
.It \fB-q, --quote\fP "" "" "" "" "" "" quote filenames with unprintable chars
.It \fB-e=, --ext1=\fP ( \fI''\fP )  %e output from x.so:func(qpath: cstr)->cstr
.It \fB-E=, --ext2=\fP ( \fI''\fP )  %E output from x.so:func(qpath: cstr)->cstr
.El
.Ss "Meta"
.Bl -hang -width MM
.It \fB-C=, --colors=\fP (\fI{}\fP)   color aliases; Syntax: name = ATTR1 ATTR2..
.It \fB-S=, --Style=\fP (\fI''\fP)    DEFINE an output style arg bundle
.It \fB-s=, --style=\fP (\fI''\fP)    APPLY an output style
.It \fB-X=, --extra=\fP (\fI''\fP)    add params from config ARG where ARG means:
.Bl -tag -width ROOT// -compact -offset 2n
.It "\fIROOT\fP."
Load any \fB.lc\fP in the same dir as being listed
.It "\fIROOT\fP/"
Load any \fB.lc\fP in any parent dir of those listed
.It "\fIROOT\fP/."
Load \fB.lc\fP in the same dir as being listed (--recurse)
.It "\fIROOT\fP//"
Load \fB.lc\fP in parent dirs of those listed (--recurse)
.El
Useful values of \fIROOT\fP are either "." for paths relative to the dir being
listed (if you have durable write access, say).  You can make a partial shadow
of a dir-tree, though, and
.Nm
will look for \fB.lc\fP relative to an alternate root.  (Examples of non-durable
write access might be /usr/lib or /dev.)
.El
.Ss "Content Generation & Filtering"
.Bl -hang -width MM
.It \fB-d, --dirs\fP            list dirs as themselves, not contents
.It \fB-r=, --recurse=\fP (\fI1\fP)   recurse N levels; 0 => unbounded
.It \fB-i=, --incl=\fP (\fI{}\fP)     kind \fINAME\fPs to include
.It \fB-x=, --excl=\fP (\fI{}\fP)     kind \fINAME\fPs to exclude
.It \fB-w=, --widest=\fP (\fI0\fP)    only list this many widest entries
in each column; 0 => do not filter.  This feature is useful to see if there are
a few files where renaming to shorter names would allow more columns.
.El
.Ss "Table Controls"
.Bl -hang -width MM
.It \fB-n=, --nColumn=\fP (\fI999\fP) max major columns to use
.It \fB-1, --n1\fP              same as \fB-n1\fP; Mostly to have a long option to bind short form \fB-1\fP commonly available in file listers.
.It \fB-P=, --padMax=\fP (\fI999\fP)  max spaces by which to pad major columns
.It \fB-W=, --width=\fP (\fI0\fP)     override auto-detected terminal width
.It \fB-D, --dense\fP           no blanks between multiple dir listings
.It \fB-u, --unzipF\fP          negate default all-after-%[fF] column zip
.It \fB-H, --header\fP          add a row at start of data with col names
.It \fB-t, --total\fP           print total of blocks before entries
.El
.Ss "Auto-Abbreviation"
.Bl -hang -width MM
.It \fB-m=, --maxName=\fP (\fI''\fP) \fIAbbreviationSpecifier\fP where an abbreviation specifier can be:
.Bl -tag -width "Number>0" -compact -offset indent
.It Em "aANYTEXT"
automatic - best unique same-location single-'*'
.It Em "Number>0"
=M - manual terminal-width M
.br
    [,head(M/2) - manual prefix length
.br
    [,tail(M-head+len(sep)) - manual suffix length
.br
    [,sep('*') - override separator, e.g. "..."
.br
    [,quoteChars]]]] - chars to be ?-pattern-quoted
.It Em "-2"
shortest unique prefix
.It Em "-3"
shortest unique suffix
.It Em "-4"
shorter of minimal prefix & suffix
.It Em "-5"
shortest 1-'*' anywhere glob with unique match
.It Em "-6"
shortest 2-'*' anywhere glob with unique match
.El
That is quite a lot.  There is much flexibility since circumstances vary enough
that any one heuristic can fail badly.  While examples here might help, there is
really no substitute for images here:
.br
  https://htmlpreview.github.io/?https://raw.githubusercontent.com/c-blake/lc/master/screenshots/src-linux-script/progression.html
.Pp
"pattern quoting" is AFAIK a term of my own invention but refers to the fact
that in many shells '?' can match any character, even shell meta-characters.
So, assuming a unique match (which
.Nm
abbreviation often ensures), one way to "quote" a shell-meta character is to
replace it with '?' which I call "pattern quoting".  In other words, if shell
auto-expansion/magic space is set up, you should be able to click or otherwise
select unique globs, hit a <TAB>-equivalent, and see just one match, at least if
the PWD is the same as what
.Nm
is rendering for.  (Of course, you need not expand before using in commands.
That is just a way to describe what is going on.)
.It \fB-M=, --maxTgt=\fP (\fI""\fP) \fIAbbreviationSpecifier\fP for symLink targets; No auto
.It \fB-U=, --maxUnm=\fP (\fI""\fP) \fIAbbreviationSpecifier\fP for user names
.It \fB-G=, --maxGnm=\fP (\fI""\fP) \fIAbbreviationSpecifier\fP for group names
.It \fB-F, --reFit\fP   expand abbrevs up to padded column widths.
Basically, abbreviate only to the extent it helps a table have fewer columns.
.El
.Ss "Miscellaneous"
.Bl -hang -width MM
.It \fB-g=, --glyph=\fP (\fI" -> "\fP) how to render arrow in %r/%R readlink formats
.It \fB-b, --binary\fP   K=size/1024, M=size/1024/1024 (vs \fI\,/1000\/\fP..)
.It \fB-L, --deref\fP    deref symLinks generally
.It \fB-l, --tgtDref\fP  fully classify \&%R formats on their own
.It \fB-p, --plain\fP    plain text; No color escape sequences
.It \fB-A, --access\fP   use 3*access(2) not st_mode for RWX perms
.It \fB--hyperlink\fP    add hyperlinks
.It \fB--version\fP      print version and exit
.El
.Sh FORMAT & ORDER CODES
.Ss "SHARED codes for BOTH format AND order specs:"
.Bl -tag -width "pMMMMpermUGO" -compact
.It CODE HEADER
DESCRIPTION
.It Em "f    Nm"
file / path name
.It Em "F    Bs"
baseName
.It Em "s    SzDv"
human readable size | dev number (if block | char).  This is rounded with
a metric-ish prefix on it (or a pair of hex numbers) to only ever occupy 4
terminal columns.
.It Em "K    Bk"
file blocks
.It Em "n    N"
link count; number of hard links | subdirs
.It Em "u    uid"
numeric uid
.It Em "U    Usr"
user name string
.It Em "g    gid"
numeric gid
.It Em "G    Grp"
group name string
.It Em "p    permUGO"
rwxr-xr-x perms for user, group, other bit banks
.It Em "a|A  a|Atm"
access time: ~ time of last read(2) to file
.It Em "m|M  m|Mtm"
modify time: ~ time of last write(2) to file
.It Em "c|C  c|Ctm"
create/change status time: ~ mtm for most file metadata
.It Em "v|V  v|Vtm"
version time = max(c, m)
.It Em "b|B  b|Btm"
birth time (~ when blocks first allocated for i-nodes)
.It Em "i    inode"
i-node number
.It Em "k    BkZ"
st_blksize
.It Em "D    Mj"
major dev number
.It Em "d    Mn"
minor dev number
.It Em "o    %o"
%allocated byte range occupied by data blocks
.El
.Ss "FORMAT ONLY 1-letter codes:"
.Bl -tag -width qMMMMpermUGO -compact
.It Em "r    ln"
readlink(2) output aka link target
.It Em "R    Ln"
like 'r' but with colorized target
.It Em "Z    SecLab"
selinux label
.It Em "S    ByDv"
size in bytes | dev number (if block | char); Overloading this column is ancient
file listing tradition.
.It Em "P    perm"
Colored, Octal Perms
.It Em "q    permUGO"
rwx perms with space separators
.It Em "Q    A"
\'+\' if a file has an ACL
.It Em "l    l"
ls-KindCode(dl-..)
.It Em "L    L"
ls-KindCode(/@\|=)
.It Em "e    e1"
Output of External Program 1
.It Em "E    e2"
Output of External Program 2
.It Em "x    XA"
stxAttrCode
.It Em "@    I"
Icon (4th :-sep Col Of --color spec)
.It Em "0-8  D0-8"
User-defined format components 0-8; See CONFIGURING
.It Em "9./  L0-2"
User-defined format components 0-2 for symLink target
.El
.Ss "ORDER ONLY 1-letter codes:"
.Bl -tag -width CODE -compact
.It CODE
DESCRIPTION
.It Em e
shortest file name (e)xtension; LAST '.' -> END of name
.It Em E
longest file name (E)xtension; FIRST '.' -> END of name
.It Em N
(N)umeric File Name
.It Em L
file Name (L)ength 
.It Em A
(A)bbreviated File Name
.It Em 0-2
file kind order Components 0-2
.It Em 3-5
file kind id Components 0-2
.It Em 6-8
symLink target order Components 0-2
.It Em 9./
symLink target file kind Components 0-2
.El
.Sh "TEXT ATTRIBUTE / COLOR SPECIFICATION"
.Ss "Basic SGR/Font Attributes"
\fIplain\fP, \fIbold\fP, \fIitalic\fP, \fIunderline\fP, \fIblink\fP, \fIinverse\fP, \fIstruck\fP, \fINONE\fP
.Ss "Basic Foreground Colors"
\fIblack\fP, \fIred\fP, \fIgreen\fP, \fIyellow\fP, \fIblue\fP, \fIpurple\fP, \fIcyan\fP, \fIwhite\fP
.Ss "Basic Background Colors"
An \fIon_\fP prefix implies using this color as the BACKGROUND color.
.Pp
So, for example, \fBbold white on_red\fP specifies what it sounds like -- bold
font white foreground text with a dark red background.
.Ss "High Intensity Colors"
UPPERCASE of the same names implies the HIGH intensity bank (for either fore- or
background colors).  Fewer terminals support this.  SGR codes are, respectively,
9x & 10x with x in [0,7] (for fore- & background).  E.g., \fBYELLOW on_red
italic\fP means render bright yellow on dark red text with italic font.
.Ss "256-color xterm Colors"
256-color xterm attrs are \fI[fb][0..23]\fP for FORE/BACKground grey scale &
\fI[fb]RGB\fP a 6x6x6 color cube; each [RGB] is on [0,5].  So, \fBf123 b20 blink\fP
means blinking red 1/5, green 2/5, blue 3/5 text on a gray 20/23 background.
.Ss "xterm/st/kitty true colors"
xterm/st/kitty true colors are \fI[fb]HHHHHH\fP (usual R,G,B mapping).  E.g.,
\fBwhite underline b081830\fP is underlined white text on Red=0x08=8/255,
Green=0x18=24/255, Blue=0x30=48/255.
.Ss "Where these can be used"
While \fB--color\fP values are the primary use case, field & strftime formats
both accept \fI%{ATTR..}CODE\fP.  E.g., \fBlc -f '%{inverse}f'\fP will list
directory entries with whatever other colorization they would have had, but with
whatever your terminal maps color inversion to overlaid.
.Sh "EXIT STATUS"
.Nm
exits with a status which is the max of 127 (the biggest non-signal exit code
on Unix) and the number of OS errors encountered collecting data (such as files
being removed after readdir but before stat).
.Sh ENVIRONMENT
.Bl -tag -width XDG_CONFIG_HOME
.It Ev CLIGEN
The path to the config file or directory for cligen CL framework configuration.
This can tune \fI--help\fP colorization, layout, and content as well as a few CL
syntax variations such as whether long options require unique prefixes or being
fully spelled out.
.It Ev LC_CONFIG
If set, this is a path to a Nim std/parsecfg configuration file or
directory containing parameters processed by every invocation of
.Nm .
If compiled with \fI-d:cgCfgToml\fP the format of this file is TOML, but you
must first have installed github.com/NimParsers/parsetoml somewhere in your \fInim
c --path:SEARCH\fP
.It Ev XDG_CONFIG_HOME
XDG directory for configuration files; ~/.config is a common choice.
.It Ev HOME
Users home directory used here as a fallback parent for .config if neither
LC_CONFIG nor XDG_CONFIG_HOME are set.
.It Ev LC
Additional command parameters for every invocation
.El
.Sh SEE ALSO
.Xr ls 1 .
Full
.Nm
documentation is linked off of github.com/c-blake/lc
.Sh HISTORY
Ideas relating to this program date back to a circa 2000 Python script system
(largely user-definable via environment variables containing lambdas) that was
too slow.  It later became a long, ugly C program & then a Nim program, partly
as a way to drive feature development in cligen (like the --Style system).
.Sh BUGS
Probably.  Please report on Github.
